apiVersion: v1
kind: Service
metadata:
  labels:
    app: guacamole
    version: v1
  name: guacamole
spec:
  ports:
  - name: port-1
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port-2
    port: 4822
    protocol: TCP
    targetPort: 4822
  selector:
    app: guacamole
  sessionAffinity: None
  type: ClusterIP
