apiVersion: v1
kind: Service
metadata:
  labels:
    app: guac-app
  name: guac-app
spec:
  ports:
  - port: 5901
    protocol: TCP
    targetPort: 5901
  selector:
    app: guac-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
